apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: product-demo
spec:
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce
      type: string
  workspaces:
    - name: source
      description: Workspace containing the source code
  steps:
    - name: build
      image: registry.redhat.io/rhel8/buildah:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -e
        buildah bud --format=docker --tls-verify=false \
          -f ./Dockerfile \
          -t $(params.IMAGE) .
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
    - name: push
      image: registry.redhat.io/rhel8/buildah:latest
      script: |
        #!/usr/bin/env bash
        set -e
        buildah push --tls-verify=false $(params.IMAGE) \
          docker://$(params.IMAGE)
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}
