apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: product-api-listener
  namespace: product-demo
spec:
  to:
    kind: Service
    name: el-product-api-listener
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
