apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: product-api-listener
  namespace: product-demo
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: github-push-binding
      template:
        ref: product-api-trigger-template
